[package]
name = "cennznet-testing"
version = "1.0.0"
authors = ["Centrality Developers <support@centrality.ai>"]
description = "Test utilities for CENNZnet node."
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0" }
wabt = "0.9.2"
cennznet-executor = { path = "../executor" }
cennznet-primitives = { path = "../primitives" }
cennznet-runtime = { path = "../runtime" }
crml-transaction-payment = { path="../crml/transaction-payment", default-features = false }
frame-system = { git = "https://github.com/plugblockchain/plug-blockchain", branch = "1.0.0-rc2" }
pallet-contracts = { git = "https://github.com/plugblockchain/plug-blockchain", branch = "1.0.0-rc2" }
pallet-grandpa = { git = "https://github.com/plugblockchain/plug-blockchain", branch = "1.0.0-rc2" }
pallet-session = { git = "https://github.com/plugblockchain/plug-blockchain", branch = "1.0.0-rc2" }
crml-staking = { version = "1.0.0",  path = "../crml/staking" }
sc-client = { git = "https://github.com/plugblockchain/plug-blockchain", branch = "1.0.0-rc2" }
sc-client-db = { git = "https://github.com/plugblockchain/plug-blockchain", branch = "1.0.0-rc2" }
sc-executor = { git = "https://github.com/plugblockchain/plug-blockchain", branch = "1.0.0-rc2" }
sp-core = { git = "https://github.com/plugblockchain/plug-blockchain", branch = "1.0.0-rc2" }
sp-io = { git = "https://github.com/plugblockchain/plug-blockchain", branch = "1.0.0-rc2" }
sp-keyring = { git = "https://github.com/plugblockchain/plug-blockchain", branch = "1.0.0-rc2" }
sp-runtime = { git = "https://github.com/plugblockchain/plug-blockchain", branch = "1.0.0-rc2" }
substrate-test-client = { git = "https://github.com/plugblockchain/plug-blockchain", branch = "1.0.0-rc2" }
