[package]
name = "trustcodes"
version = "0.1.0"
authors = ["Centrality Developers <support@centrality.ai>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true }
parity-codec = { version = "3.5.4", default-features = false }
primitives = { package = "substrate-primitives", git = "https://github.com/cennznet/plug-blockchain", default-features = false }
rstd = { package="sr-std", git = "https://github.com/cennznet/plug-blockchain", default-features = false }
runtime_io = { package="sr-io", git = "https://github.com/cennznet/plug-blockchain", default-features = false }
runtime_primitives = { package="sr-primitives", git = "https://github.com/cennznet/plug-blockchain", default-features = false }
support = { package="srml-support", git = "https://github.com/cennznet/plug-blockchain", default-features = false }
system = { package="srml-system", git = "https://github.com/cennznet/plug-blockchain", default-features = false }

[features]
default = ["std"]
std = [
	"serde",
	"parity-codec/std",
	"primitives/std",
	"rstd/std",
	"runtime_io/std",
	"runtime_primitives/std",
	"support/std",
	"system/std",
]
